# Generated by Django 4.2.10 on 2024-02-14 11:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ffinderapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="age",
        ),
        migrations.AddField(
            model_name="player",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="player",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="date_of_birth",
            field=models.DateField(default="1990-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="player",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="student_photos/"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="profile_photos/"),
        ),
        migrations.AlterField(
            model_name="player",
            name="position",
            field=models.CharField(
                choices=[
                    ("gk", "Goalkeeper"),
                    (
                        "def",
                        [
                            ("cb", "Center Back"),
                            ("rb", "Right Back"),
                            ("lb", "Left Back"),
                        ],
                    ),
                    (
                        "mid",
                        [
                            ("dm", "Defensive Midfielder"),
                            ("cm", "Central Midfielder"),
                            ("am", "Attacking Midfielder"),
                        ],
                    ),
                    (
                        "att",
                        [
                            ("st", "Striker"),
                            ("rw", "Right Winger"),
                            ("lw", "Left winger"),
                        ],
                    ),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_photos/"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
