# Generated by Django 4.2.10 on 2024-03-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0004_application_customuser_listing_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teamprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="/Users/mcolley/Developmentproject/ffinderpro/ffinderapp/static/media/logo.jpeg",
                null=True,
                upload_to="team_profile_photos/",
            ),
        ),
    ]
