# Generated by Django 4.2.10 on 2024-03-24 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0005_alter_teamprofile_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="listing",
            name="team_photo",
        ),
        migrations.RemoveField(
            model_name="team",
            name="location",
        ),
        migrations.AddField(
            model_name="listing",
            name="city",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="listing",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="listing_photos/"),
        ),
        migrations.AddField(
            model_name="listing",
            name="positions",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="listing",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="teamprofile",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
    ]
