# Generated by Django 4.2.10 on 2024-03-26 12:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0006_remove_listing_team_photo_remove_team_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerprofile",
            name="position",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="previous_clubs",
            field=models.TextField(blank=True, null=True),
        ),
    ]
