# Generated by Django 4.2.10 on 2024-03-28 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0007_playerprofile_position_playerprofile_previous_clubs"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="team_members",
                to="ffinderapp.team",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/listing_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="playerprofile",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/player_photos/"
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="team_association",
                to="ffinderapp.customuser",
            ),
        ),
        migrations.AlterField(
            model_name="teamprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="/Users/mcolley/Developmentproject/ffinderpro/ffinderapp/static/media/logo.jpeg",
                null=True,
                upload_to="media/team_profile_photos/",
            ),
        ),
    ]
