# Generated by Django 4.2.10 on 2024-04-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0009_customuser_photo_alter_playerprofile_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="listing_photos/"),
        ),
    ]
