# Generated by Django 4.2.10 on 2024-04-03 15:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0010_alter_listing_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/listing_photos/"
            ),
        ),
    ]
