# Generated by Django 4.2.10 on 2024-04-12 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0012_playerlisting_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="user_profile",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="ffinderapp.customuser",
            ),
        ),
    ]
