# Generated by Django 4.2.10 on 2024-04-22 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ffinderapp", "0015_alter_listing_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerlisting",
            name="user_profile",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
