# Generated by Django 4.2.10 on 2024-04-24 02:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0016_playerlisting_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/player_photos"
            ),
        ),
        migrations.AlterField(
            model_name="teamprofile",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="/media/",
                null=True,
                upload_to="media/team_profile_photos/",
            ),
        ),
    ]
