# Generated by Django 4.2.10 on 2024-04-24 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0017_alter_customuser_photo_alter_teamprofile_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerlisting",
            name="contact_number",
            field=models.CharField(default="", max_length=15),
        ),
    ]
