# Generated by Django 4.2.10 on 2024-04-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ffinderapp", "0018_playerlisting_contact_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="playerlisting",
            name="location",
            field=models.CharField(default="", max_length=100),
        ),
    ]
